AWSTemplateFormatVersion: '2010-09-09'
Description: AWS DataSync CloudFormation Sample - FSx Windows to FSx Windows - Destination Region
Metadata:
  License:
    Description: |
      Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

      Permission is hereby granted, free of charge, to any person obtaining a copy of this
      software and associated documentation files (the "Software"), to deal in the Software
      without restriction, including without limitation the rights to use, copy, modify,
      merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
      permit persons to whom the Software is furnished to do so.

      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
      INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
      PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
      HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
      OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - securityGroupId
          - fsxwFSid
          - fsxwPath
          - secretName
    ParameterLabels:
      fsxwFSid:
        default: 'FSx file system ID'
      fsxwPath:
        default: 'Path on FSx file system'
      secretName:
        default: 'Secret name for credentials'
      securityGroupId:
        default: 'Security group'

Parameters:
  securityGroupId:
    Description: 'Security group to be used by DataSync for the FSx location'
    Type: AWS::EC2::SecurityGroup::Id
  fsxwFSid:
    Description: 'File system ID for the FSx for Windows file server'
    Type: String
  fsxwPath:
    Description: 'The path to copy data to on the FSx for Windows file server'
    Type: String
    Default: '/share'
  secretName:
    Description: 'Secret name with user credentials'
    Type: String

Resources:

  FSxWindowsLocation:
    Type: AWS::DataSync::LocationFSxWindows
    Properties:
      User: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:username}}'
      Password: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:password}}'
      Domain: !Sub '{{resolve:secretsmanager:${secretName}:SecretString:domain}}'
      FsxFilesystemArn: !Sub arn:${AWS::Partition}:fsx:${AWS::Region}:${AWS::AccountId}:file-system/${fsxwFSid}
      SecurityGroupArns:
        - !Sub arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:security-group/${securityGroupId}
      Subdirectory: !Ref fsxwPath

Outputs:
  locationArn:
    Description: Location ARN
    Value: !Ref FSxWindowsLocation
  locationUri:
    Description: Location URI
    Value: !GetAtt FSxWindowsLocation.LocationUri
